name: Bug report
description: Report a reproducible bug in Vifei Suite
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Use this form for reproducible defects.
        For vulnerabilities, use `SECURITY.md` and private reporting.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-paragraph description of the issue.
      placeholder: What happened, and why this is a bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact commands and inputs needed to reproduce.
      placeholder: |
        1. Run `...`
        2. Import fixture `...`
        3. Observe `...`
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Include OS, terminal/multiplexer, Rust toolchain.
      placeholder: ubuntu 24.04, zsh, tmux 3.4, rustc 1.86.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and evidence
      description: Paste exact output, exit codes, and relevant artifacts.
      placeholder: Include `ansi.capture`, `viewmodel.hash`, or refusal report snippets when relevant.
  - type: checkboxes
    id: checks
    attributes:
      label: Safety checks
      options:
        - label: I removed or redacted secrets, tokens, and private data.
          required: true
        - label: I searched existing issues for duplicates.
          required: true
