#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="${1:-.tmp/launch-media-bundle-$(date -u +%Y%m%dT%H%M%SZ)}"
RUN_DIR="$OUT_DIR/demo-proof"
ASSET_DIR="$OUT_DIR/assets/readme"
CAST_DIR="$OUT_DIR/casts"
TRUST_DIR="$OUT_DIR/trust-cut"
VISUAL_DIR="$OUT_DIR/visual-cut"
TRANSCRIPT="$OUT_DIR/COMMAND_TRANSCRIPT.txt"
NOTES="$OUT_DIR/REPLAY_NOTES.md"
MAP_MD="$OUT_DIR/COMMAND_ASSET_MAP.md"
INDEX_JSON="$OUT_DIR/bundle-index.json"

mkdir -p "$OUT_DIR" "$ASSET_DIR"
: > "$TRANSCRIPT"

run_cmd() {
  echo "$ $*" | tee -a "$TRANSCRIPT"
  "$@" 2>&1 | tee -a "$TRANSCRIPT"
}

echo "[bundle] output dir: $OUT_DIR"

run_cmd scripts/demo_quickcheck.sh "$RUN_DIR"
run_cmd cargo run -p vifei-tour --bin media_provenance -- \
  --verify "$RUN_DIR/media-provenance.json" \
  --base-dir "$RUN_DIR"
run_cmd scripts/testing/check_media_hygiene.sh "$RUN_DIR"
run_cmd scripts/demo/trust_demo_cut.sh "$TRUST_DIR" fixtures/small-session.jsonl
run_cmd scripts/demo/visual_showcase_cut.sh "$VISUAL_DIR"

cp docs/assets/readme/incident-lens.txt "$ASSET_DIR/"
cp docs/assets/readme/forensic-lens.txt "$ASSET_DIR/"
cp docs/assets/readme/truth-hud-degraded.txt "$ASSET_DIR/"
cp docs/assets/readme/export-refusal.txt "$ASSET_DIR/"
cp docs/assets/readme/artifacts-view.txt "$ASSET_DIR/"

if command -v asciinema >/dev/null 2>&1; then
  mkdir -p "$CAST_DIR"
  run_cmd scripts/capture_showcase_cast.sh --fast "$CAST_DIR"
else
  echo "[bundle] asciinema not installed; skipping cast capture" | tee -a "$TRANSCRIPT"
fi

python3 - "$OUT_DIR" "$RUN_DIR" "$INDEX_JSON" <<'PY'
import hashlib
import json
import subprocess
import sys
from pathlib import Path

out_dir = Path(sys.argv[1])
run_dir = Path(sys.argv[2])
index_path = Path(sys.argv[3])

def digest(path: Path) -> str:
    return hashlib.blake2s(path.read_bytes()).hexdigest()

bundle_files = []
for path in sorted(out_dir.rglob("*")):
    if not path.is_file():
        continue
    if path == index_path:
        continue
    bundle_files.append(
        {
            "path": str(path.relative_to(out_dir)).replace("\\", "/"),
            "blake2s": digest(path),
        }
    )

git_sha = (
    subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    .stdout.strip()
)

index = {
    "schema_version": "vifei-launch-bundle-v1",
    "git_sha": git_sha,
    "run_dir": "demo-proof",
    "trust_cut_dir": "trust-cut",
    "visual_cut_dir": "visual-cut",
    "media_provenance": "demo-proof/media-provenance.json",
    "files": bundle_files,
}
index_path.write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
PY

cat > "$MAP_MD" <<EOF
# Command to Asset Map

## Trust cut

\`\`\`bash
scripts/demo/trust_demo_cut.sh $TRUST_DIR fixtures/small-session.jsonl
\`\`\`

- \`trust-cut/TRUST_DEMO_SUMMARY.txt\`
- \`trust-cut/tour-a/metrics.json\`
- \`trust-cut/tour-a/viewmodel.hash\`
- \`trust-cut/refusal-refused.json\`

## Visual cut

\`\`\`bash
scripts/demo/visual_showcase_cut.sh $VISUAL_DIR
\`\`\`

- \`visual-cut/VISUAL_SHOWCASE_SUMMARY.txt\`
- \`assets/readme/incident-lens.txt\`
- \`assets/readme/forensic-lens.txt\`
- \`assets/readme/truth-hud-degraded.txt\`
- \`assets/readme/export-refusal.txt\`
- \`assets/readme/artifacts-view.txt\`

## Full proof bundle

\`\`\`bash
scripts/demo/package_launch_bundle.sh $OUT_DIR
\`\`\`

- \`demo-proof/media-provenance.json\`
- \`COMMAND_TRANSCRIPT.txt\`
- \`REPLAY_NOTES.md\`
- \`bundle-index.json\`
EOF

cat > "$NOTES" <<EOF
# Launch Bundle Replay Notes

This bundle is generated by:

\`\`\`bash
scripts/demo/package_launch_bundle.sh $OUT_DIR
\`\`\`

## Verify trust signals

\`\`\`bash
cat $RUN_DIR/viewmodel.hash
python3 - <<'PY'
import json
from pathlib import Path
m = json.loads(Path("$RUN_DIR/tour/metrics.json").read_text())
print("tier_a_drops=", m["tier_a_drops"])
print("degradation_level_final=", m["degradation_level_final"])
PY
\`\`\`

## Verify provenance and hygiene

\`\`\`bash
cargo run -p vifei-tour --bin media_provenance -- \\
  --verify $RUN_DIR/media-provenance.json --base-dir $RUN_DIR
scripts/testing/check_media_hygiene.sh $RUN_DIR
\`\`\`

## Transcript

See \`COMMAND_TRANSCRIPT.txt\` for exact command execution trace.
EOF

echo "[bundle] PASS: launch bundle ready at $OUT_DIR"
